### Configuration for Alacritty
# ! Author: JP (Juan Pablo Rodriguez)
# ! Github: krajp54

# * Enviroment variable for the terminal instance
env:
  TERM: alacritty

# * Settings for the terminal window instance
window:
  dimensions:
    columns: 80
    lines: 40

  padding:
    x: 8
    y: 8

  title: Alacritty

  class:
    instance: Alacritty
    general: Alacritty

# * Maximum number of lines in the scrollback buffer.
scrolling:
  history: 2000

# * Font configuration
font:
  normal:
    family: RobotoMono Nerd Font
    style: Regular

  bold:
    family: RobotoMono Nerd Font
    style: Bold

  italic:
    family: RobotoMono Nerd Font
    style: Italic

  bold_italic:
    family: RobotoMono Nerd Font
    style: Bold Italic

  size: 10.0

  # Space between characters
  offset:
    x: 0
    y: 0

# * Draw blod text using bright color variants.
draw_bold_text_with_bright_colors: true

# * Colorscheme for the terminal
# Configured using the alacritty-colorscheme utility
# The folder "colors" contain all the colorschemes available

colors:
  # COLORSCHEME: base16-twilight-256.yml
  # Default colors
  primary:
    background: '0x1e1e1e'
    foreground: '0xa7a7a7'

  # Colors the cursor will use if `custom_cursor_colors` is true
  normal:
    black: '0x1e1e1e'
    red: '0xcf6a4c'
    green: '0x8f9d6a'
    yellow: '0xf9ee98'
    blue: '0x7587a6'
    magenta: '0x9b859d'
    cyan: '0xafc4db'
    white: '0xa7a7a7'

  # Bright colors
  bright:
    black: '0x5f5a60'
    red: '0xcf6a4c'
    green: '0x8f9d6a'
    yellow: '0xf9ee98'
    blue: '0x7587a6'
    magenta: '0x9b859d'
    cyan: '0xafc4db'
    white: '0xffffff'

  cursor:
    text: '0x1e1e1e'
    cursor: '0xa7a7a7'

  # Normal colors
  dim:
    black: '0x232323'
    red: '0x74423f'
    green: '0x5e6547'
    yellow: '0x8b7653'
    blue: '0x556b79'
    magenta: '0x6e4962'
    cyan: '0x5c8482'
    white: '0x828282'
  indexed_colors:
    - {index: 16, color: '0xcda869'}
    - {index: 17, color: '0x9b703f'}
    - {index: 18, color: '0x323537'}
    - {index: 19, color: '0x464b50'}
    - {index: 20, color: '0x838184'}
    - {index: 21, color: '0xc3c3c3'}
background_opacity: 0.92

# * Default cursor on the terminal emulator
cursor:
  # Values for `style`:
  #   - ▇ Block
  #   - _ Underline
  #   - | Beam
  style: Block
# * List of keybindings available
#key_bindings:
#- { key: Paste,                                action: Paste          }
#- { key: Copy,                                 action: Copy           }
#- { key: L,         mods: Control,             action: ClearLogNotice }
#- { key: L,         mods: Control, mode: ~Vi,  chars: "\x0c"          }
#- { key: PageUp,    mods: Shift,   mode: ~Alt, action: ScrollPageUp,  }
#- { key: PageDown,  mods: Shift,   mode: ~Alt, action: ScrollPageDown }
#- { key: Home,      mods: Shift,   mode: ~Alt, action: ScrollToTop,   }
#- { key: End,       mods: Shift,   mode: ~Alt, action: ScrollToBottom }
# Vi Mode
#- { key: Space,  mods: Shift|Control, mode: Vi, action: ScrollToBottom          }
#- { key: Space,  mods: Shift|Control,           action: ToggleViMode            }
#- { key: Escape,                      mode: Vi, action: ClearSelection          }
#- { key: I,                           mode: Vi, action: ScrollToBottom          }
#- { key: I,                           mode: Vi, action: ToggleViMode            }
#- { key: Y,      mods: Control,       mode: Vi, action: ScrollLineUp            }
#- { key: E,      mods: Control,       mode: Vi, action: ScrollLineDown          }
#- { key: G,                           mode: Vi, action: ScrollToTop             }
#- { key: G,      mods: Shift,         mode: Vi, action: ScrollToBottom          }
#- { key: B,      mods: Control,       mode: Vi, action: ScrollPageUp            }
#- { key: F,      mods: Control,       mode: Vi, action: ScrollPageDown          }
#- { key: U,      mods: Control,       mode: Vi, action: ScrollHalfPageUp        }
#- { key: D,      mods: Control,       mode: Vi, action: ScrollHalfPageDown      }
#- { key: Y,                           mode: Vi, action: Copy                    }
#- { key: Y,                           mode: Vi, action: ClearSelection          }
#- { key: Copy,                        mode: Vi, action: ClearSelection          }
#- { key: V,                           mode: Vi, action: ToggleNormalSelection   }
#- { key: V,      mods: Shift,         mode: Vi, action: ToggleLineSelection     }
#- { key: V,      mods: Control,       mode: Vi, action: ToggleBlockSelection    }
#- { key: V,      mods: Alt,           mode: Vi, action: ToggleSemanticSelection }
#- { key: Return,                      mode: Vi, action: Open                    }
#- { key: K,                           mode: Vi, action: Up                      }
#- { key: J,                           mode: Vi, action: Down                    }
#- { key: H,                           mode: Vi, action: Left                    }
#- { key: L,                           mode: Vi, action: Right                   }
#- { key: Up,                          mode: Vi, action: Up                      }
#- { key: Down,                        mode: Vi, action: Down                    }
#- { key: Left,                        mode: Vi, action: Left                    }
#- { key: Right,                       mode: Vi, action: Right                   }
#- { key: Key0,                        mode: Vi, action: First                   }
#- { key: Key4,   mods: Shift,         mode: Vi, action: Last                    }
#- { key: Key6,   mods: Shift,         mode: Vi, action: FirstOccupied           }
#- { key: H,      mods: Shift,         mode: Vi, action: High                    }
#- { key: M,      mods: Shift,         mode: Vi, action: Middle                  }
#- { key: L,      mods: Shift,         mode: Vi, action: Low                     }
#- { key: B,                           mode: Vi, action: SemanticLeft            }
#- { key: W,                           mode: Vi, action: SemanticRight           }
#- { key: E,                           mode: Vi, action: SemanticRightEnd        }
#- { key: B,      mods: Shift,         mode: Vi, action: WordLeft                }
#- { key: W,      mods: Shift,         mode: Vi, action: WordRight               }
#- { key: E,      mods: Shift,         mode: Vi, action: WordRightEnd            }
#- { key: Key5,   mods: Shift,         mode: Vi, action: Bracket                 }
#- { key: Slash,                       mode: Vi, action: SearchForward           }
#- { key: Slash,  mods: Shift,         mode: Vi, action: SearchBackward          }
#- { key: N,                           mode: Vi, action: SearchNext              }
#- { key: N,      mods: Shift,         mode: Vi, action: SearchPrevious          }
# (Windows, Linux, and BSD only)
#- { key: V,        mods: Control|Shift,           action: Paste            }
#- { key: C,        mods: Control|Shift,           action: Copy             }
#- { key: F,        mods: Control|Shift,           action: SearchForward    }
#- { key: B,        mods: Control|Shift,           action: SearchBackward   }
#- { key: C,        mods: Control|Shift, mode: Vi, action: ClearSelection   }
#- { key: Insert,   mods: Shift,                   action: PasteSelection   }
#- { key: Key0,     mods: Control,                 action: ResetFontSize    }
#- { key: Equals,   mods: Control,                 action: IncreaseFontSize }
#- { key: Add,      mods: Control,                 action: IncreaseFontSize }
#- { key: Subtract, mods: Control,                 action: DecreaseFontSize }
#- { key: Minus,    mods: Control,                 action: DecreaseFontSize }
# (Windows only)
#- { key: Return,   mods: Alt,           action: ToggleFullscreen }
# (macOS only)
#- { key: K,      mods: Command, mode: ~Vi, chars: "\x0c"            }
#- { key: Key0,   mods: Command,            action: ResetFontSize    }
#- { key: Equals, mods: Command,            action: IncreaseFontSize }
#- { key: Add,    mods: Command,            action: IncreaseFontSize }
#- { key: Minus,  mods: Command,            action: DecreaseFontSize }
#- { key: K,      mods: Command,            action: ClearHistory     }
#- { key: V,      mods: Command,            action: Paste            }
#- { key: C,      mods: Command,            action: Copy             }
#- { key: C,      mods: Command, mode: Vi,  action: ClearSelection   }
#- { key: H,      mods: Command,            action: Hide             }
#- { key: M,      mods: Command,            action: Minimize         }
#- { key: Q,      mods: Command,            action: Quit             }
#- { key: W,      mods: Command,            action: Quit             }
#- { key: N,      mods: Command,            action: SpawnNewInstance }
#- { key: F,      mods: Command|Control,    action: ToggleFullscreen }
#- { key: F,      mods: Command,            action: SearchForward    }
#- { key: B,      mods: Command,            action: SearchBackward   }
