### Configuration for Alacritty
# ! Author: JP (Juan Pablo Rodriguez)
# ! Github: krajp54

# * Enviroment variable for the terminal instance
env:
  TERM: alacritty

# * Settings for the terminal window instance
window:
  dimensions:
    columns: 120
    lines: 40

  padding:
    x: 8
    y: 8

  title: Alacritty

  class:
    instance: Alacritty
    general: Alacritty

# * Maximum number of lines in the scrollback buffer.
scrolling:
  history: 2000
  multiplier: 3

# * Font configuration
font:
  normal:
    family: CaskaydiaCove Nerd Font
    style: Regular

  bold:
    family: CaskaydiaCove Nerd Font
    style: Bold

  italic:
    family: CaskaydiaCove Nerd Font
    style: Italic

  bold_italic:
    family: CaskaydiaCove Nerd Font
    style: Bold Italic

  size: 8.0

  # Space between characters
  offset:
    x: 0
    y: 0

# * Draw blod text using bright color variants.
draw_bold_text_with_bright_colors: true

# * Colorscheme for the terminal
# Configured using the alacritty-colorscheme utility
# The folder "colors" contain all the colorschemes available
colors:
  name: Derp
  author: ""
  primary:
    background: "#000000"
    foreground: "#ffffff"
  cursor:
    text: "#000000"
    cursor: "#ffffff"
  normal:
    black: "#111111"
    red: "#d36265"
    green: "#aece91"
    yellow: "#e7e18c"
    blue: "#5297cf"
    magenta: "#963c59"
    cyan: "#5e7175"
    white: "#bebebe"
  bright:
    black: "#666666"
    red: "#ef8171"
    green: "#cfefb3"
    yellow: "#fff796"
    blue: "#74b8ef"
    magenta: "#b85e7b"
    cyan: "#a3babf"
    white: "#ffffff"
background_opacity: 0.80

# * Default cursor on the terminal emulator
cursor:
  # Values for `style`:
  #   - ▇ Block
  #   - _ Underline
  #   - | Beam
  style: Underline
# * List of keybindings available
#key_bindings:
#- { key: Paste,                                action: Paste          }
#- { key: Copy,                                 action: Copy           }
#- { key: L,         mods: Control,             action: ClearLogNotice }
#- { key: L,         mods: Control, mode: ~Vi,  chars: "\x0c"          }
#- { key: PageUp,    mods: Shift,   mode: ~Alt, action: ScrollPageUp,  }
#- { key: PageDown,  mods: Shift,   mode: ~Alt, action: ScrollPageDown }
#- { key: Home,      mods: Shift,   mode: ~Alt, action: ScrollToTop,   }
#- { key: End,       mods: Shift,   mode: ~Alt, action: ScrollToBottom }
# Vi Mode
#- { key: Space,  mods: Shift|Control, mode: Vi, action: ScrollToBottom          }
#- { key: Space,  mods: Shift|Control,           action: ToggleViMode            }
#- { key: Escape,                      mode: Vi, action: ClearSelection          }
#- { key: I,                           mode: Vi, action: ScrollToBottom          }
#- { key: I,                           mode: Vi, action: ToggleViMode            }
#- { key: Y,      mods: Control,       mode: Vi, action: ScrollLineUp            }
#- { key: E,      mods: Control,       mode: Vi, action: ScrollLineDown          }
#- { key: G,                           mode: Vi, action: ScrollToTop             }
#- { key: G,      mods: Shift,         mode: Vi, action: ScrollToBottom          }
#- { key: B,      mods: Control,       mode: Vi, action: ScrollPageUp            }
#- { key: F,      mods: Control,       mode: Vi, action: ScrollPageDown          }
#- { key: U,      mods: Control,       mode: Vi, action: ScrollHalfPageUp        }
#- { key: D,      mods: Control,       mode: Vi, action: ScrollHalfPageDown      }
#- { key: Y,                           mode: Vi, action: Copy                    }
#- { key: Y,                           mode: Vi, action: ClearSelection          }
#- { key: Copy,                        mode: Vi, action: ClearSelection          }
#- { key: V,                           mode: Vi, action: ToggleNormalSelection   }
#- { key: V,      mods: Shift,         mode: Vi, action: ToggleLineSelection     }
#- { key: V,      mods: Control,       mode: Vi, action: ToggleBlockSelection    }
#- { key: V,      mods: Alt,           mode: Vi, action: ToggleSemanticSelection }
#- { key: Return,                      mode: Vi, action: Open                    }
#- { key: K,                           mode: Vi, action: Up                      }
#- { key: J,                           mode: Vi, action: Down                    }
#- { key: H,                           mode: Vi, action: Left                    }
#- { key: L,                           mode: Vi, action: Right                   }
#- { key: Up,                          mode: Vi, action: Up                      }
#- { key: Down,                        mode: Vi, action: Down                    }
#- { key: Left,                        mode: Vi, action: Left                    }
#- { key: Right,                       mode: Vi, action: Right                   }
#- { key: Key0,                        mode: Vi, action: First                   }
#- { key: Key4,   mods: Shift,         mode: Vi, action: Last                    }
#- { key: Key6,   mods: Shift,         mode: Vi, action: FirstOccupied           }
#- { key: H,      mods: Shift,         mode: Vi, action: High                    }
#- { key: M,      mods: Shift,         mode: Vi, action: Middle                  }
#- { key: L,      mods: Shift,         mode: Vi, action: Low                     }
#- { key: B,                           mode: Vi, action: SemanticLeft            }
#- { key: W,                           mode: Vi, action: SemanticRight           }
#- { key: E,                           mode: Vi, action: SemanticRightEnd        }
#- { key: B,      mods: Shift,         mode: Vi, action: WordLeft                }
#- { key: W,      mods: Shift,         mode: Vi, action: WordRight               }
#- { key: E,      mods: Shift,         mode: Vi, action: WordRightEnd            }
#- { key: Key5,   mods: Shift,         mode: Vi, action: Bracket                 }
#- { key: Slash,                       mode: Vi, action: SearchForward           }
#- { key: Slash,  mods: Shift,         mode: Vi, action: SearchBackward          }
#- { key: N,                           mode: Vi, action: SearchNext              }
#- { key: N,      mods: Shift,         mode: Vi, action: SearchPrevious          }
# (Windows, Linux, and BSD only)
#- { key: V,        mods: Control|Shift,           action: Paste            }
#- { key: C,        mods: Control|Shift,           action: Copy             }
#- { key: F,        mods: Control|Shift,           action: SearchForward    }
#- { key: B,        mods: Control|Shift,           action: SearchBackward   }
#- { key: C,        mods: Control|Shift, mode: Vi, action: ClearSelection   }
#- { key: Insert,   mods: Shift,                   action: PasteSelection   }
#- { key: Key0,     mods: Control,                 action: ResetFontSize    }
#- { key: Equals,   mods: Control,                 action: IncreaseFontSize }
#- { key: Add,      mods: Control,                 action: IncreaseFontSize }
#- { key: Subtract, mods: Control,                 action: DecreaseFontSize }
#- { key: Minus,    mods: Control,                 action: DecreaseFontSize }
# (Windows only)
#- { key: Return,   mods: Alt,           action: ToggleFullscreen }
# (macOS only)
#- { key: K,      mods: Command, mode: ~Vi, chars: "\x0c"            }
#- { key: Key0,   mods: Command,            action: ResetFontSize    }
#- { key: Equals, mods: Command,            action: IncreaseFontSize }
#- { key: Add,    mods: Command,            action: IncreaseFontSize }
#- { key: Minus,  mods: Command,            action: DecreaseFontSize }
#- { key: K,      mods: Command,            action: ClearHistory     }
#- { key: V,      mods: Command,            action: Paste            }
#- { key: C,      mods: Command,            action: Copy             }
#- { key: C,      mods: Command, mode: Vi,  action: ClearSelection   }
#- { key: H,      mods: Command,            action: Hide             }
#- { key: M,      mods: Command,            action: Minimize         }
#- { key: Q,      mods: Command,            action: Quit             }
#- { key: W,      mods: Command,            action: Quit             }
#- { key: N,      mods: Command,            action: SpawnNewInstance }
#- { key: F,      mods: Command|Control,    action: ToggleFullscreen }
#- { key: F,      mods: Command,            action: SearchForward    }
#- { key: B,      mods: Command,            action: SearchBackward   }

shell:
  program: /bin/zsh
  args:
    - --login
